Infinite scroll error
EarthCubeGeochron/Sparrow pull request #106
Opened 2021-04-19 23:25 UTC by Idzikowski-Casey

Work in progress! Has a hacky way of telling if there are no results versus if the results are still loading. There is an attempt at catching the error that occurs with nesting in an api call and using the `AppToaster` component to display it. The error being caught is a `can't read data of undefined` because the response from the api is undefined. The api call hangs for a while and then it breaks with a bad gateway 502 network error.

2021-04-20 21:45 UTC, davenquinn requested changes
I'm mostly fine with this I suppose. But ideally you'd provide the error object (not just its message) to a custom component whose job it is to render errors appropriately.

2021-04-20 21:45 UTC, davenquinn commented on frontend/src/components/infinite-scroll/infinite-api-view.ts
> +  if (error) {
Do we really not have a component you can borrow/share from the `ErrorBoundary` component? I'd like to see us use the same underlying component to render errors across the application...

2021-04-20 21:45 UTC, davenquinn commented on frontend/src/components/infinite-scroll/main.styl
> +.api-error
Hard-coding colors should be avoided unless necessary...

2021-04-21 16:40 UTC, Idzikowski-Casey commented on frontend/src/components/infinite-scroll/infinite-api-view.ts
> +  if (error) {
I broke the ErrorBoundry component down into a no-state functional component that only handles the error object. Now it's easier to share across the codebase.

2021-04-21 16:55 UTC, davenquinn approved these changes
Love it!

2021-04-21 16:55 UTC, merged