add depth limit on joinedload recursion
EarthCubeGeochron/Sparrow pull request #107
Opened 2021-04-20 21:05 UTC by Idzikowski-Casey

2021-04-20 21:39 UTC, davenquinn requested changes
Make depth configurable

2021-04-20 21:39 UTC, davenquinn commented on backend/sparrow/interface/schema.py
> +        if depth > 1:
Maybe pass in max_depth as well....

2021-04-20 21:39 UTC, davenquinn commented on backend/sparrow_tests/test_project_import.py
> +        #assert len(statements) == 1 # statements is 80
So wait, did you add a failing test, or did you make the failing test pass? Seems like the latter.

It'd be nice if you made depth configurable. Then we could still have this test pass but also configure the depth to 1 or 2 in application code.

2021-04-20 21:44 UTC, Idzikowski-Casey commented on backend/sparrow/interface/schema.py
> +        if depth > 1:
Okay, I will do that. A depth > 1 creates the same backend exiting we are seeing.

2021-04-20 21:45 UTC, Idzikowski-Casey commented on backend/sparrow_tests/test_project_import.py
> +        #assert len(statements) == 1 # statements is 80
Agreed, I think we can make depth configurable at schema initialization.

2021-04-20 21:48 UTC, davenquinn commented on backend/sparrow_tests/test_project_import.py
> +        #assert len(statements) == 1 # statements is 80
or better yet just make it configurable in the calling code, e.g., `schema.query_options(join_depth=2)`.

2021-04-20 22:17 UTC, Idzikowski-Casey commented on backend/sparrow_tests/test_project_import.py
> +        #assert len(statements) == 1 # statements is 80
Okay, so now this test is failing, and the `max_depth` is configurable on the `schema.nested_relationships()` called in this test. So far changing the depth to a high number hasn't changed `len(statements)`.

2021-04-20 22:23 UTC, davenquinn requested changes
Can you make the default `max_depth=None` which doesn't limit recursion by default, but limit recursion to `max_depth=1` in the API? Then the test doesn't have to set an arbitrary max depth...

2021-04-20 22:23 UTC, davenquinn commented
Once that last change is made you can go ahead and merge, assuming tests pass..

2021-04-21 02:06 UTC, Idzikowski-Casey commented on backend/sparrow/api/endpoints/model.py
> +        q = q.options(*list(schema.query_options(max_depth=1)))
Set API to have a max_dept of 1

2021-04-21 02:08 UTC, Idzikowski-Casey commented on backend/sparrow/interface/schema.py
> +    def _nested_relationships(self, *, nests=None, current_depth=0, max_depth=None):
max_depth has a default value of None

2021-04-21 02:08 UTC, Idzikowski-Casey commented on backend/sparrow/interface/schema.py
> +    def query_options(self, max_depth=None):
max_depth is configurable from a few methods

2021-04-21 02:10 UTC, merged