Map errors
EarthCubeGeochron/Sparrow pull request #88
Opened 2021-04-05 16:30 UTC by Idzikowski-Casey

This branch has fixes including map isolation (closes #86), has a specific GeoJSON sample route as a temporary solution to the slow API issue, and has a new frame `shortSiteTitle` that is used in the Map navbar, defaults to the first 5 characters of the normal site title with `...` appended to end. 

For now, the filtering on the map has been removed. Will make an issue and assign it to me (@Idzikowski-Casey).

2021-04-06 21:38 UTC, davenquinn requested changes
Overall this is good but there are a few changes I'd like to see...

Still not a huge fan of the GeoJSON route but it'll work for now I guess.

2021-04-06 21:38 UTC, davenquinn commented on frontend/src/map/map-area.tsx
> +  const initialData = useAPIv2Result("/core_view/geojson");
Should have a more descriptive name: `geojson` is the type of output. `all_samples`?

2021-04-06 21:38 UTC, davenquinn commented on frontend/src/map/components/MarkerCluster.tsx
> +    // }));
Any reason why we're not just deleting this?

2021-04-06 21:38 UTC, davenquinn commented on frontend/src/components/page-skeleton/navbar.ts
> +const ShortSiteTitle = () => {
Instead of hard-coding ellipses, can you do it via css?  Will be cleaner and then the component will be responsive by size. https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

2021-04-06 21:38 UTC, davenquinn commented on frontend/src/components/page-skeleton/navbar.ts
> +  return h(NavLink, { to: "/" }, h(Frame, { id: "shortSiteTitle" }, [content]));
Wrap the outer frame with a span or something here, to add ellipses via css. That way any overflow will have ellipses...

2021-04-06 21:38 UTC, davenquinn commented on backend/sparrow/map_endpoint/__init__.py
> +                a.append(v)
This for loop is not particularly straightforward...

2021-04-06 21:38 UTC, davenquinn commented on backend/sparrow/map_endpoint/__init__.py
> +class MapGeoJSONEndpoint(SparrowCorePlugin):
Medium term, GeoJSON should be a core capability of the v2 API, and this endpoint will be removed. Maybe make a github issue to track this...

2021-04-08 14:52 UTC, Idzikowski-Casey commented on frontend/src/map/components/MarkerCluster.tsx
> +    // }));
Well, this was a quick and hacky way of turning the response from `models/sample` into valid GeoJSON that's compatible with Mapbox. This code will be needed again once we speed up the `models/sample` route.

2021-04-12 21:23 UTC, davenquinn requested changes
OK I will let you merge this after we make a new issue to figure out a way to also allow us to do query filtering. All the UI changes are good (except for the width thing), but I am very unsatisfied by the state of the API right now. This depends on other issues like #95 being resolved of course.

2021-04-12 21:23 UTC, davenquinn commented on backend/sparrow/map_endpoint/__init__.py
> +            # r is an object with the geojson as the value
See if you can restructure this as a list comprehension somehow. I don't know why you need to have a _nested_ loop in particular. Results sets are flat, and you shouldn't need to do a nested loop.

2021-04-12 21:23 UTC, davenquinn commented on backend/sparrow/map_endpoint/__init__.py
>          query = sqlfile.read()
Use helpers to load query files if possible. Or create a new helper in `sparrow.database.util` if you do this more than once.

2021-04-12 21:23 UTC, davenquinn commented on frontend/src/components/page-skeleton/module.styl
> +  width 67px
you shouldn't have to hard-code width.

2021-04-30 16:44 UTC, merged